# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: far-edge-kubelet

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'

    main: ./cmd/far-edge-kubelet
    ldflags:
      - -extldflags "-static"
      - -X main.buildVersion={{ .Summary }}
      - -X main.buildTime={{ .Date }}
    tags:
      - netgo
      - osusergo

dockers:
  - id: main-amd64
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:latest-amd64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-amd64
    extra_files:
      - deploy/configuration-data
    dockerfile: Dockerfile
    use: buildx
  - id: main-arm64
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:latest-arm64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-arm64
    extra_files:
      - deploy/configuration-data
    dockerfile: Dockerfile
    use: buildx
  - id: main-arm
    goarch: arm
    goarm: '7'
    build_flag_templates:
      - --platform=linux/arm/v7
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:latest-arm-v7
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-arm-v7
    extra_files:
      - deploy/configuration-data
    dockerfile: Dockerfile
    use: buildx

docker_manifests:
  - id: tag
    name_template: ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-amd64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-arm64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-arm-v7
  - id: latest
    name_template: ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:latest
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-amd64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-arm64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-arm-v7
  - id: major
    name_template: ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Major }}
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-amd64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-arm64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-arm-v7
  - id: minor
    name_template: 'ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Major }}.{{ .Minor }}'
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-amd64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-arm64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet:{{ .Tag }}-arm-v7

checksum:
  split: true

archives:
  - id: binaries
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: fraunhoferportugal
    name: far-edge-kubelet
  
  draft: true
